version: "3.8"

services:
  myurls:
    build: .
    image: jiong/myurls
    restart: unless-stopped
    command: bundle exec unicorn -c config/unicorn.rb
    ports:
      - "127.0.0.1:9292:9292"
    volumes:
      - ./db:/app/db
    environment:
      - APP_ENV=production
      - RACK_ENV=production
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9292"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
