version: "3"
services:
  myurls:
    image: jiong/myurls
    restart: "always"
    ports:
      - 9292:9292
    command: bundle exec unicorn -c config/unicorn.rb
    volumes:
      - ./db/production.sqlite3:/app/db/production.sqlite3